DROP DATABASE IF EXISTS HECKANSWER;
CREATE DATABASE HECKANSWER;

USE HECKANSWER;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
    session VARCHAR(64) NOT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
    id INT NOT NULL AUTO_INCREMENT,
    userid INT NOT NULL,
    title VARCHAR(128) NOT NULL,
    url VARCHAR(128) NOT NULL,
    body VARCHAR(4096) NOT NULL,
    score INT NOT NULL,
    parentid INT NOT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS VOTE;
CREATE TABLE VOTE (
    id INT NOT NULL AUTO_INCREMENT,
    userid INT NOT NULL,
    postid INT NOT NULL,
    value INT NOT NULL,
    PRIMARY KEY (`id`)
);